theme: minima
title: An amazing title
author: Vat Evaaa
email: vatever_email@some_domain.com
description: > # this means to ignore newlines until "baseurl:"
  Life is an amazing wonder on cosmological scale.
  I am very much looking forward to enjoy it to my fulliest!
  :)
  
# social links
twitter_username: @twitter_handle
github_username:  @Vatevaaa

show_excerpts: true # set to false to remove excerpts on the homepage
